[GitHubEnterprise-3.9] Update to 1.1.4-b65de54831446d196d0701f96ddb91f6 from 1.1.4-c9dcce17059a71c975472e31acae9880 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 518f96                                                                                 SPEC: extracted 2 commits from history                                                                                 DONE: completed
WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [61851:7]

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (22388:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (22511:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (22431:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (22911:20)
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[M] description (42653:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ ├─┬GET
│ │ │ └──[M] description (22696:20)
│ │ └─┬PATCH
│ │   └──[M] description (22732:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│   └─┬GET
│     └──[M] description (22289:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (51350:16)
│   └──[M] description (51356:20)
├─┬project-created
│ └─┬POST
│   ├──[M] summary (51883:16)
│   └──[M] description (51889:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (51122:16)
│   └──[M] description (51128:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (51198:16)
│   └──[M] description (51204:20)
├─┬security-advisory-published
│ └─┬POST
│   └──[M] summary (57599:16)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (51807:16)
│   └──[M] description (51813:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (51503:16)
│   └──[M] description (51509:20)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (52035:16)
│   └──[M] description (52041:20)
├─┬secret-scanning-alert-location-created
│ └──POST
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (51959:16)
│   └──[M] description (51965:20)
├─┬security-advisory-updated
│ └─┬POST
│   ├──[M] summary (57671:16)
│   └──[M] description (57675:20)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (51579:16)
│   └──[M] description (51585:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (52111:16)
│   └──[M] description (52117:20)
├─┬security-advisory-withdrawn
│ └─┬POST
│   └──[M] summary (57744:16)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (51655:16)
│   └──[M] description (51661:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (51731:16)
│   └──[M] description (51737:20)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (51274:16)
│   └──[M] description (51280:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (51426:16)
│   └──[M] description (51432:20)
└─┬Components
  ├─┬actions-workflow-access-to-repository
  │ └─┬access_level
  │   └──[M] description (70432:24)
  ├─┬code-scanning-ref-full
  │ ├──[M] pattern (72862:16)❌
  │ └──[M] description (72859:20)
  └─┬app-permissions
    ├──[-] properties (60704:9)❌
    ├──[-] properties (60718:9)❌
    ├──[-] properties (60949:9)❌
    ├──[-] properties (60956:9)❌
    ├──[-] properties (60963:9)❌
    ├──[-] properties (60970:9)❌
    ├──[-] properties (60977:9)❌
    ├──[-] properties (60872:9)❌
    ├──[-] properties (60984:9)❌
    └──[-] properties (60990:9)❌

Date: 12/08/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
webhooks         | 32            | 0
components       | 13            | 11
paths            | 8             | 0

❌  11 Breaking changes out of 53
INFO: Modifications: 43
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered