[GitHubEnterprise-3.7] Update to 1.1.4-924699702976a0153c0900e14e113800 from 1.1.4-a3c06b548eba345287efb1b13c620d6d Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 0389da                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [57810:7]
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (20512:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (20635:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (20937:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (20555:20)
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[M] description (39280:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│   └─┬GET
│     └──[M] description (20412:20)
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (48395:16)
│   └──[M] description (48401:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (47558:16)
│   └──[M] description (47564:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (47939:16)
│   └──[M] description (47945:20)
├─┬security-advisory-withdrawn
│ └─┬POST
│   └──[M] summary (53794:16)
├─┬security-advisory-published
│ └─┬POST
│   └──[M] summary (53649:16)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (48091:16)
│   └──[M] description (48097:20)
├─┬security-advisory-updated
│ └─┬POST
│   ├──[M] summary (53721:16)
│   └──[M] description (53725:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (47786:16)
│   └──[M] description (47792:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (47862:16)
│   └──[M] description (47868:20)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (48471:16)
│   └──[M] description (48477:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (48547:16)
│   └──[M] description (48553:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (48167:16)
│   └──[M] description (48173:20)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (48015:16)
│   └──[M] description (48021:20)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (47710:16)
│   └──[M] description (47716:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (47634:16)
│   └──[M] description (47640:20)
├─┬project-created
│ └─┬POST
│   ├──[M] summary (48319:16)
│   └──[M] description (48325:20)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (48243:16)
│   └──[M] description (48249:20)
└─┬Components
  ├─┬code-scanning-ref-full
  │ ├──[M] pattern (67808:16)❌
  │ └──[M] description (67805:20)
  └─┬app-permissions
    ├──[-] properties (56677:9)❌
    ├──[-] properties (56691:9)❌
    ├──[-] properties (56908:9)❌
    ├──[-] properties (56915:9)❌
    ├──[-] properties (56922:9)❌
    ├──[-] properties (56929:9)❌
    ├──[-] properties (56936:9)❌
    ├──[-] properties (56831:9)❌
    ├──[-] properties (56943:9)❌
    └──[-] properties (56949:9)❌

Date: 12/08/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 6             | 0
webhooks         | 32            | 0
components       | 12            | 11

❌  11 Breaking changes out of 50
INFO: Modifications: 40
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered