[GitHubEnterprise-3.10] Update to 1.1.4-8a044bab1bdccc55d8fbe8ab39c44fc0 from 1.1.4-701bcacf986496f5da76dea8a35d5d79 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/organization-variables
│ │ └─┬GET
│ │   └──[M] description (17730:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (18112:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (18300:20)
│ │ └─┬DELETE
│ │   └──[M] description (18334:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   └──[M] description (17530:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/admin/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (18063:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (36460:20)
│ │ └─┬POST
│ │   └──[M] description (36508:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (18220:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (215369:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (215369:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (18362:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (18444:20)
│ │ ├─┬POST
│ │ │ └──[M] description (18391:20)
│ │ └─┬DELETE
│ │   └──[M] description (18499:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (18530:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (18878:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (19481:20)
│ │ └─┬POST
│ │   └──[M] description (19528:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (19583:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (19662:20)
│ │ └─┬PATCH
│ │   └──[M] description (19617:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/environments
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (215308:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └──[M] description (18148:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (18258:20)
│ ├─┬/admin/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (224622:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (224622:20)
│ └─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│   ├─┬GET
│   │ └──[M] description (36563:20)
│   ├─┬DELETE
│   │ └──[M] description (36642:20)
│   └─┬PATCH
│     └──[M] description (36597:20)
└─┬Components
  └─┬environment
    └─┬protection_rules
      └─┬Schema
        └─┬ANYOF
          └──[-] properties (76891:17)❌

Date: 09/26/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 51            | 0
components       | 1             | 1
❌  1 Breaking changes out of 52
INFO: Modifications: 51
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered