[GitHubEnterprise-3.10] Update to 1.1.4-a5443b5869cf2e49bb71770363fd1191 from 1.1.4-dfb2d23c854f88418b9c92d345ba3730 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (226073:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (76972:14)❌
├─┬user-created
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (60534:9)
├─┬user-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (60604:9)
└─┬Components
  └──[-] schemas (76972:7)❌

Date: 09/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 2             | 1
webhooks         | 2             | 0
components       | 1             | 1
❌  2 Breaking changes out of 5
INFO: Modifications: 4
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered