[GitHubEnterprise-3.14] Update to 1.1.4-1716058b6fa04c91e7ec9ca76a7996d2 from 1.1.4-0db954ca7aa760e1c9ee3a6575105048 Detected Schema changes:
```
├─┬Paths
│ ├─┬/search/issues
│ │ └─┬GET
│ │   └──[➖] parameters (217954:13)❌
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[🔀] description (218242:20)
│ └─┬/zen
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         ├──[➕] content (47986:15)
│         └──[➖] content (47987:15)❌
└─┬Components
  └──[➖] parameters (217954:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 2                |
| components       | 1             | 1                |

Date: 03/01/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _5_
- **Modifications**: _1_
- **Removals**: _3_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered