[GitHubEnterprise-3.15] Update to 1.1.4-c839dc4b91fdd6e7b4bb4312c26a3e3d from 1.1.4-55f74f3e5247a80d845e796bbe3a0f26 Detected Schema changes:
```
└─┬Components
  └─┬repository-rule-pull-request
    └─┬parameters
      └──[➖] properties (77585:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 1             | 1                |

Date: 03/25/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered