[GitHubEnterprise-3.13] Update to 1.1.4-802a0cd5a04204e42ef5ea0492e36a70 from 1.1.4-65c7d90809c912f318fd98e5a759353c Detected Schema changes:
```
└─┬Components
  └─┬webhook-release-edited
    └─┬changes
      └──[➖] properties (181816:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 1             | 1                |

Date: 03/04/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered