[GitHubEnterprise-3.14] Update to 1.1.4-8137cb0f7b4d2c9a7e11798086b95b2a from 1.1.4-104eead85eed7e03a026852edc095233 Detected Schema changes:
```
├─┬personal-access-token-request-created
│ └─┬POST
│   ├──[🔀] summary (56868:16)
│   └─┬Extensions
│     └──[🔀] x-github (56926:9)
├─┬personal-access-token-request-approved
│ └─┬POST
│   ├──[🔀] summary (56737:16)
│   └─┬Extensions
│     └──[🔀] x-github (56795:9)
├─┬personal-access-token-request-denied
│ └─┬POST
│   ├──[🔀] summary (56933:16)
│   └─┬Extensions
│     └──[🔀] x-github (56991:9)
├─┬personal-access-token-request-cancelled
│ └─┬POST
│   ├──[🔀] summary (56802:16)
│   └─┬Extensions
│     └──[🔀] x-github (56861:9)
└─┬Components
  └─┬repository-rule-pull-request
    └─┬parameters
      └─┬allowed_merge_methods
        └─┬Schema
          ├──[➖] enum (76773:19)❌
          ├──[➖] enum (76774:19)❌
          └──[➖] enum (76775:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 3             | 3                |
| webhooks         | 8             | 0                |

Date: 03/20/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _11_
- **Modifications**: _8_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered