[GitHubEnterprise-3.8] Update to 1.1.4-14f5457f585c6f7a63a03d6f331061d7 from 1.1.4-3ca42ad655bd3942766b14f42849fa5e Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/migrations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬exclude
│ │           └──[M] description (11324:32)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         └──[M] value (209222:9)
│   └─┬PUT
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (209222:9)
├──check-run-rerequested
└─┬Components
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (83133:28)
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (81912:28)
  ├─┬webhook-deployment-status-created
  │ └─┬check_run
  │   └─┬conclusion
  │     └──[M] description (88941:28)
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (83710:28)
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (84217:28)
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[+] properties (71931:17)
  ├─┬full-repository
  │ └──[+] required (67041:9)❌
  ├─┬webhook-code-scanning-alert-appeared-in-branch
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (83452:28)
  └─┬webhook-check-suite-requested
    └─┬check_suite
      └─┬conclusion
        └──[M] description (82526:28)

Date: 10/05/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 0
components       | 9             | 1
❌  1 Breaking changes out of 12
INFO: Modifications: 10
INFO: Additions: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered