[GitHubEnterprise-3.9] Update to 1.1.4 (hash: f8b11ae17a31e6c384ad9d8d831faea2) from 1.1.4 (hash: 666ecf28261cc4d9a19b77a514f8de10) Detected Schema changes:
├─┬Paths
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬subject_type
│             ├──[+] enum (32217:21)
│             ├──[+] enum (32218:21)
│             ├──[-] enum (32217:21)❌
│             └──[-] enum (32218:21)❌
└─┬Components
  ├──[-] schemas (83071:7)❌
  ├──[-] schemas (83058:7)❌
  ├─┬webhook-secret-scanning-alert-location-created
  │ └─┬alert
  │   └──[M] $ref (79658:13)❌
  ├─┬webhook-secret-scanning-alert-created
  │ └─┬alert
  │   └──[M] $ref (79658:13)❌
  ├─┬webhook-secret-scanning-alert-revoked
  │ └─┬alert
  │   └──[M] $ref (79658:13)❌
  ├─┬webhook-secret-scanning-alert-resolved
  │ └─┬alert
  │   └──[M] $ref (184600:11)❌
  └─┬webhook-secret-scanning-alert-reopened
    └─┬alert
      └──[M] $ref (79658:13)❌

Date: 07/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 2
components       | 7             | 7
❌  9 Breaking changes out of 11
INFO: Modifications: 5
INFO: Removals: 4
INFO: Additions: 2
INFO: Breaking Removals: 4
INFO: Breaking Modifications: 5

ERROR: breaking changes discovered