[GitHubEnterprise-3.7] Update to 1.1.4-58c817ab817b7a21ad6dbe53cfac43ef from 1.1.4-d7d27bb64fd6d090bc0563dca0ed52e5 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (25040:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (25058:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (25165:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (25176:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (25073:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25153:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (25317:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25338:9)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-extra-repository-information
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           ├──[M] value (212136:9)
│ │           └──[+] value (212136:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (25275:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25304:9)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[-] codes (216233:7)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (25351:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25365:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (25406:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25417:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (25192:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (25208:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (25223:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25261:9)
│ ├─┬/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default-response
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           ├──[M] value (200866:9)
│ │           └──[+] value (200866:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-repository-permissions
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           ├──[M] value (200405:9)
│ │           └──[+] value (200405:9)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (24903:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (24927:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (24941:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (25026:9)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│   └─┬POST
│     ├─┬External Docs
│     │ └──[M] url (25379:14)
│     └─┬Extensions
│       └──[M] x-github (25390:9)
├─┬pull-request-edited
│ └─┬POST
│   └──[M] description (49711:20)
└─┬Components
  ├─┬repository-webhooks
  │ └──[-] properties (77319:9)❌
  ├─┬team-repository
  │ └──[+] properties (64165:9)
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └──[-] properties (185441:13)❌
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └──[-] properties (186616:13)❌
  ├─┬webhook-team-created
  │ └─┬repository
  │   └──[-] properties (186028:13)❌
  ├─┬webhook-fork
  │ └─┬forkee
  │   └─┬ALLOF
  │     └──[-] properties (90580:15)❌
  ├─┬webhook-team-edited
  │ └─┬repository
  │   └──[-] properties (187259:13)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └──[-] properties (110212:17)❌
  ├─┬webhook-push
  │ └─┬repository
  │   └──[-] properties (177343:13)❌
  ├─┬webhook-team-removed-from-repository
  │ └─┬repository
  │   └──[-] properties (187848:13)❌
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └──[-] properties (105868:17)❌
  └─┬job
    └─┬status
      └──[-] enum (65283:13)❌

Date: 11/06/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 82            | 1
webhooks         | 1             | 0
components       | 12            | 12
❌  13 Breaking changes out of 95
INFO: Modifications: 79
INFO: Removals: 12
INFO: Additions: 4
INFO: Breaking Removals: 12

ERROR: breaking changes discovered