[GitHubEnterprise-3.7] Update to 1.1.4-217eba5bd4c7f01c411f911fc37b26f6 from 1.1.4-ef080e38cf33c1e05f59441363784b5f Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (15737:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (206395:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (206395:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (15817:20)
│ │ └─┬DELETE
│ │   └──[M] description (15851:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (16047:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (16395:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (15701:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/admin/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215354:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (215354:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (15652:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (15879:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (15961:20)
│ │ ├─┬POST
│ │ │ └──[M] description (15908:20)
│ │ └─┬DELETE
│ │   └──[M] description (16016:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   └──[M] description (15229:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (15775:20)
│ └─┬/admin/hooks/{hook_id}/pings
│   └─┬POST
│     └─┬Parameters
│       └──[M] description (215354:20)
├──check-run-completed
└─┬Components
  └─┬environment
    └─┬protection_rules
      └─┬Schema
        └─┬ANYOF
          └──[-] properties (69748:17)❌

Date: 09/26/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 38            | 0
components       | 1             | 1
❌  1 Breaking changes out of 39
INFO: Modifications: 38
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered