[GitHubEnterprise-3.14] Update to 1.1.4-e9e561609727200e583d8b0b8e5feeb1 from 1.1.4-15f794337a26277abf54b138881ec64f Detected Schema changes:
```
└─┬Components
  └─┬api-overview
    └─┬domains
      └──[➖] properties (73057:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 1             | 1                |

Date: 12/17/24 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered