[GitHubEnterprise-3.10] Update to 1.1.4-ba65b0b23bbc2a3e41a9bedb93b5eb23 from 1.1.4-b2e8e10041873f18a27f697a2fe87a2e Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (215381:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (215381:9)
│ ├─┬/orgs/{org}/migrations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬exclude
│ │           └──[M] description (12014:32)
│ └─┬/repos/{owner}/{repo}/environments
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (215319:9)
└─┬Components
  ├─┬full-repository
  │ └──[+] required (71701:9)❌
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[+] properties (76896:17)
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (87781:28)
  ├─┬webhook-code-scanning-alert-appeared-in-branch
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (88707:28)
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (88388:28)
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (89472:28)
  ├─┬webhook-deployment-status-created
  │ └─┬check_run
  │   └─┬conclusion
  │     └──[M] description (94229:28)
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (87167:28)
  ├─┬code-scanning-default-setup-update
  │ └─┬languages
  │   └──[M] description (74653:24)
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (88965:28)
  └─┬code-scanning-default-setup
    └─┬languages
      └──[M] description (74606:24)

Date: 10/05/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 0
components       | 11            | 1
❌  1 Breaking changes out of 15
INFO: Modifications: 13
INFO: Additions: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered