[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 3059c72b96522e28ad4e057b42cce4d6) from 1.1.4 (hash: a1ffd8a78284f3066064905b42991b32) Detected Schema changes:
└─┬Components
  ├─┬organization-full
  │ └──[-] required (64142:9)❌
  ├─┬webhook-check-suite-rerequested
  │ └──[+] properties (81583:9)
  ├─┬team-organization
  │ └──[-] required (65325:9)❌
  ├─┬webhook-check-suite-requested
  │ └──[+] properties (80967:9)
  └─┬webhook-check-suite-completed
    └──[+] properties (80350:9)

Date: 07/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 5             | 2
❌ 2 Breaking changes out of 5

ERROR: breaking changes discovered