[GitHubEnterprise-3.6] Update to 1.1.4-62923369a0400f70e7b31c853e54e80c from 1.1.4-a3c692ddcb92a94d187be5255e12cd25 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (72587:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (72587:9)
│ └─┬/orgs/{org}/migrations
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬exclude
│             └──[M] description (10392:32)
└─┬Components
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[+] properties (52364:17)
  └─┬full-repository
    └──[+] required (47936:9)❌

Date: 10/05/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 0
components       | 2             | 1
❌  1 Breaking changes out of 5
INFO: Modifications: 3
INFO: Additions: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered