[GitHubEnterprise-3.13] Update to 1.1.4-3d4394c11aa41626a6e266db909dd9d7 from 1.1.4-1e4171c4fa0a2799e195f6bc1881cf84 Detected Schema changes:
```
├─┬Paths
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193846:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193846:9)
│ ├─┬/enterprises/{enterprise}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (216105:7)❌
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           └──[➖] value (193954:9)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           └──[➖] value (193954:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (216105:7)❌
│ ├─┬/orgs/{org}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (216105:7)❌
│ ├─┬/enterprises/{enterprise}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193846:9)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193846:9)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           ├──[🔀] value (193945:9)
│ │           └──[➖] value (193954:9)
│ ├─┬/repos/{owner}/{repo}/pages/deployments
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[➕] value (34573:19)
│ └─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/runners
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (193846:9)
└─┬Components
  └─┬runner
    └──[➖] properties (68625:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 27            | 3                |
| components       | 1             | 1                |

Date: 02/06/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _28_
- **Modifications**: _20_
- **Removals**: _7_
- **Additions**: _1_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered