[GitHubEnterprise-3.6] Update to 1.1.4 (hash: 895deed01610e80ef091314b27224594) from 1.1.4 (hash: 1a5d15c5835fee18bcd41280ef545ffa) Detected Schema changes:
└─┬Paths
  ├─┬/repos/{owner}/{repo}/contents/{path}
  │ └─┬GET
  │   └──[M] description (21834:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25805:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (25841:14)
  ├─┬/repos/{owner}/{repo}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26982:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (27020:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
  │ ├─┬POST
  │ │ └─┬External Docs
  │ │   └──[M] url (25984:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26032:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26790:14)
  ├─┬/search/code
  │ └─┬GET
  │   └──[M] description (33287:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (19679:14)
  ├─┬/enterprises/{enterprise}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (4941:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26266:14)
  │ ├─┬PUT
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (26397:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       └─┬ONEOF
  │ │         └─┬labels
  │ │           └──[M] description (26413:34)
  │ ├─┬POST
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (26308:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ ├──[M] type (26357:23)❌
  │ │       │ └──[-] properties (26318:19)❌
  │ │       └─┬ONEOF
  │ │         ├──[M] type (26319:23)❌
  │ │         └──[+] properties (26321:19)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26487:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19847:14)
  ├─┬/repos/{owner}/{repo}/issues/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25718:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
  │ ├─┬PUT
  │ │ └─┬External Docs
  │ │   └──[M] url (26562:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26615:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26517:14)
  ├─┬/repos/{owner}/{repo}/deployments
  │ └─┬POST
  │   └──[M] description (22593:20)
  ├─┬/repos/{owner}/{repo}/assignees
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16810:14)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25471:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (25549:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (25502:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (19343:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (19374:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (19449:36)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21615:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (31267:14)
  ├─┬/repos/{owner}/{repo}/issues
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25200:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (25296:14)
  ├─┬/orgs/{org}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (11502:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (31168:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (31208:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26228:14)
  ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25755:14)
  ├─┬/orgs/{org}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (8082:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26085:14)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
  │ └─┬POST
  │   └──[M] description (29129:20)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   ├─┬External Docs
  │   │ └──[M] url (19043:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (19125:36)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19638:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27571:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (27661:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (27601:14)
  ├─┬/repos/{owner}/{repo}/issues/comments
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25420:14)
  ├─┬/orgs/{org}/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (10060:14)
  ├─┬/orgs/{org}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (8120:20)
  ├─┬/user/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (36741:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19879:14)
  ├─┬/repos/{owner}/{repo}/milestones
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27433:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (27500:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (27685:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (15355:20)
  ├─┬/enterprises/{enterprise}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (4577:20)
  ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (15322:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26121:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (26169:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (31121:14)
  ├─┬/repos/{owner}/{repo}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16852:14)
  ├─┬/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (6082:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21550:14)
  ├─┬/enterprises/{enterprise}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (4615:20)
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   ├──[M] description (19717:20)
  │   └─┬External Docs
  │     └──[M] url (19726:14)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   ├──[M] description (19773:20)
  │   └─┬External Docs
  │     └──[M] url (19784:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (19939:14)
  └─┬/repos/{owner}/{repo}/labels/{name}
    ├─┬GET
    │ └─┬External Docs
    │   └──[M] url (27087:14)
    ├─┬DELETE
    │ └─┬External Docs
    │   └──[M] url (27181:14)
    └─┬PATCH
      └─┬External Docs
        └──[M] url (27121:14)

Date: 07/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 77            | 3
❌ 3 Breaking changes out of 77

ERROR: breaking changes discovered