[GitHubEnterprise-3.11] Update to 1.1.4-475831f01dfccc4232d8f163ec3347d4 from 1.1.4-c130f6d882ed81d2bb9f0a52fabb02d9 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 2f5805                                                                                 SPEC: extracted 2 commits from history                                                                                 DONE: completed
WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [64885:7]

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[M] description (19086:20)
│ ├─┬/teams/{team_id}/members/{username}
│ │ └─┬PUT
│ │   └──[M] description (40308:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (16065:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (15917:32)
│ ├─┬/users/{username}/suspended
│ │ └─┬PUT
│ │   └──[M] description (45059:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ └─┬PUT
│ │   └──[M] description (13682:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/jobs
│ │ └─┬GET
│ │   └──[M] description (19476:20)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (43886:20)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (40787:20)
│ ├─┬/user/following/{username}
│ │ └─┬PUT
│ │   └──[M] description (41371:20)
│ ├─┬/gists/{gist_id}/star
│ │ └─┬PUT
│ │   └──[M] description (6362:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ └─┬PUT
│ │   └──[M] description (30881:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[M] description (20387:20)
│ ├─┬/user/starred/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (43701:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (24623:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs
│ │ └─┬GET
│ │   └──[M] description (19313:20)
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (40626:32)
│ └─┬/users/{username}/site_admin
│   └─┬PUT
│     └──[M] description (44872:20)
└─┬Components
  ├─┬code-scanning-organization-alert-items
  │ └─┬rule
  │   └──[M] $ref (66625:13)❌
  └─┬code-scanning-alert-rule-summary
    └──[-] properties (66653:9)❌

Date: 12/16/23 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 18            | 0
components       | 2             | 2

❌  2 Breaking changes out of 20
INFO: Modifications: 19
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered