[GitHubEnterprise-3.5] Update to 1.1.4 (hash: 78bbb32c2bfb9306a1dd7d31b9eef7e8) from 1.1.4 (hash: 7400a97b39d10fa07857f724ccec0232) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21138:22)
│ ├─┬/repos/{owner}/{repo}/git/refs/{ref}
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (23749:22)
│ ├─┬/repos/{owner}/{repo}/git/ref/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (23590:22)
│ ├─┬/user/starred/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[-] description (36837:20)
│ │ └─┬DELETE
│ │   └──[-] description (36898:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/status
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21320:22)
│ ├─┬/repos/{owner}/{repo}/git/matching-refs/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (23547:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/statuses
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21362:22)
│ ├─┬/repos/{owner}/{repo}/subscription
│ │ └─┬GET
│ │   └──[-] description (31211:20)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   ├──[M] summary (23467:16)
│ │   └──[M] description (23468:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21254:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21183:22)
│ └─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│   └─┬GET
│     └──[M] description (20490:20)
└─┬Components
  └──[-] parameters (78659:7)❌

Date: 06/14/23 | Commit: New: etc/specs/GitHubEnterprise-3.5/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.5/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 14            | 0
components       | 1             | 1
❌ 1 Breaking changes out of 15

ERROR: breaking changes discovered