[GitHubEnterprise-3.11] Update to 1.1.4-3be240f188d592ffe6c58927a2a011e4 from 1.1.4-d810efa450e64b6193d7452eaa525971 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 12684d
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (222282:7)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └──[M] description (37036:20)
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └──[M] description (44805:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └──[M] description (13803:20)
│ └─┬/user/repos
│   └─┬POST
│     └──[M] description (42964:20)
└─┬Components
  ├──[-] schemas (83896:7)❌
  ├──[-] schemas (83950:7)❌
  ├──[-] schemas (83994:7)❌
  ├──[-] schemas (83922:7)❌
  ├──[-] schemas (83936:7)❌
  ├──[-] schemas (83909:7)❌
  ├──[-] schemas (83964:7)❌
  ├──[-] schemas (83979:7)❌
  ├─┬repository-webhooks
  │ └─┬size
  │   └──[M] description (86906:24)
  ├─┬secret-scanning-location
  │ ├─┬type
  │ │ ├──[-] enum (84022:13)❌
  │ │ ├──[-] enum (84024:13)❌
  │ │ ├──[-] enum (84025:13)❌
  │ │ ├──[-] enum (84018:13)❌
  │ │ ├──[-] enum (84019:13)❌
  │ │ ├──[-] enum (84021:13)❌
  │ │ ├──[-] enum (84020:13)❌
  │ │ ├──[-] enum (84023:13)❌
  │ │ └──[M] description (83900:24)
  │ └─┬details
  │   ├──[-] oneOf (83979:7)❌
  │   ├──[-] oneOf (83807:7)❌
  │   ├──[-] oneOf (83883:7)❌
  │   ├──[-] oneOf (83909:7)❌
  │   ├──[-] oneOf (83857:7)❌
  │   ├──[-] oneOf (83950:7)❌
  │   ├──[-] oneOf (83964:7)❌
  │   ├──[-] oneOf (83922:7)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83865:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83802:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (83878:20)❌
  │   └─┬ONEOF
  │     └──[M] $ref (83852:20)❌
  ├─┬minimal-repository
  │ └─┬size
  │   └──[M] description (69398:24)
  ├─┬repository
  │ └─┬size
  │   └──[M] description (65069:24)
  ├─┬full-repository
  │ └─┬size
  │   └──[M] description (71446:24)
  └─┬api-overview
    └─┬domains
      └──[-] properties (69124:13)❌

Date: 12/02/23 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 0
components       | 34            | 29

❌  29 Breaking changes out of 39
INFO: Modifications: 14
INFO: Removals: 25
INFO: Breaking Removals: 25
INFO: Breaking Modifications: 4

ERROR: breaking changes discovered