[GitHubEnterprise-3.14] Update to 1.1.4-bd6820e03c74d20458b48da696efedec from 1.1.4-e9e561609727200e583d8b0b8e5feeb1 Detected Schema changes:
```
└─┬Components
  ├─┬code-scanning-default-setup-update
  │ └─┬languages
  │   └─┬Schema
  │     └──[➖] enum (81794:15)❌
  └─┬code-scanning-default-setup
    └─┬languages
      └─┬Schema
        └──[➖] enum (81739:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |

Date: 12/20/24 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered