[GitHubEnterprise-3.15] Update to 1.1.4-677a17027c4f55b2f25358b32f865398 from 1.1.4-8ccdb4a501a9f3713872e86b010424b2 Detected Schema changes:
```
└─┬Components
  ├──[➖] schemas (92452:7)❌
  ├──[➖] schemas (92401:7)❌
  └─┬exemption-request
    ├─┬metadata
    │ ├──[➖] anyOf (92421:7)❌
    │ ├──[➖] anyOf (92436:7)❌
    │ ├──[➖] anyOf (92452:7)❌
    │ ├──[➕] oneOf (92401:7)
    │ └──[➕] oneOf (92416:7)
    ├─┬request_type
    │ └──[➖] enum (92527:13)❌
    └─┬exemption_request_data
      └──[➖] oneOf (92401:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 9             | 7                |

Date: 03/13/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _7_ out of _9_
- **Removals**: _7_
- **Additions**: _2_
- **Breaking Removals**: _7_

ERROR: breaking changes discovered