[GitHubEnterprise-3.14] Update to 1.1.4-d5ac2a68d76d323d5182cd11d4daf614 from 1.1.4-1716058b6fa04c91e7ec9ca76a7996d2 Detected Schema changes:
```
└─┬Components
  ├──[➖] schemas (92025:7)❌
  ├──[➖] schemas (91987:7)❌
  ├─┬exemption-request
  │ ├─┬metadata
  │ │ └──[➖] oneOf (92025:7)❌
  │ ├─┬exemption_request_data
  │ │ └──[➖] oneOf (91987:7)❌
  │ ├─┬number
  │ │ └──[🔀] type (92041:17)❌
  │ └─┬request_type
  │   └──[➖] enum (92100:13)❌
  └─┬webhook-release-edited
    └─┬changes
      └──[➖] properties (183682:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 7             | 7                |

Date: 03/04/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _7_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered