[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 400b378fef7791d436cd6447533940e8) from 1.1.4 (hash: c409ab671a89b9d0a7c845dff4e2bbaf) Detected Schema changes:
├─┬Paths
│ ├─┬/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6315:14)
│ ├─┬/enterprises/{enterprise}/{security_product}/{enablement}
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (5227:14)
│ ├─┬/search/code
│ │ └─┬GET
│ │   └──[M] description (35356:20)
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28741:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (28779:14)
│ ├─┬/repos/{owner}/{repo}/check-suites
│ │ └─┬POST
│ │   ├──[M] description (21180:20)
│ │   └─┬External Docs
│ │     └──[M] url (21189:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (28549:14)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (23045:14)
│ ├─┬/repos/{owner}/{repo}/check-suites/preferences
│ │ └─┬PATCH
│ │   ├──[M] description (21236:20)
│ │   └─┬External Docs
│ │     └──[M] url (21247:14)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (27514:14)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (33139:14)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (27179:14)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (8481:20)
│ ├─┬/enterprises/{enterprise}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (4622:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27230:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27308:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (27261:14)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (23110:14)
│ ├─┬/repos/{owner}/{repo}/assignees/{assignee}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18288:14)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5144:14)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10965:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (27844:14)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (21142:14)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29330:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29420:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (29360:14)
│ ├─┬/repos/{owner}/{repo}/milestones
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29192:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (29259:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27564:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (27600:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28025:14)
│ │ ├─┬PUT
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28156:14)
│ │ │ └─┬Requestbody
│ │ │   └─┬application/json
│ │ │     └─┬Schema
│ │ │       ├─┬ONEOF
│ │ │       │ └─┬labels
│ │ │       │   ├──[-] description (28169:34)
│ │ │       │   └─┬Schema
│ │ │       │     ├──[+] required (28196:25)❌
│ │ │       │     ├──[M] type (28191:29)❌
│ │ │       │     └──[+] properties (28193:25)
│ │ │       ├─┬ONEOF
│ │ │       │ ├──[+] items (28200:19)❌
│ │ │       │ ├──[M] type (28197:23)❌
│ │ │       │ ├──[+] minItems (28198:27)❌
│ │ │       │ └──[-] properties (28184:19)❌
│ │ │       └─┬ONEOF
│ │ │         ├──[-] items (28197:19)❌
│ │ │         ├──[M] type (28167:23)❌
│ │ │         ├──[-] minItems (28195:27)❌
│ │ │         └──[+] properties (28169:19)
│ │ ├─┬POST
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28067:14)
│ │ │ └─┬Requestbody
│ │ │   └─┬application/json
│ │ │     └─┬Schema
│ │ │       ├─┬ONEOF
│ │ │       │ ├──[+] items (28094:19)❌
│ │ │       │ ├──[M] type (28091:23)❌
│ │ │       │ ├──[+] minItems (28092:27)❌
│ │ │       │ └──[-] properties (28077:19)❌
│ │ │       ├─┬ONEOF
│ │ │       │ ├──[-] items (28091:19)❌
│ │ │       │ ├──[M] type (28116:23)❌
│ │ │       │ └──[-] minItems (28089:27)❌
│ │ │       ├─┬ONEOF
│ │ │       │ ├──[M] type (28095:23)❌
│ │ │       │ └──[+] properties (28097:19)
│ │ │       ├─┬ONEOF
│ │ │       │ ├──[+] items (28110:19)❌
│ │ │       │ ├──[M] type (28107:23)❌
│ │ │       │ ├──[+] minItems (28108:27)❌
│ │ │       │ └──[-] properties (28094:19)❌
│ │ │       └─┬ONEOF
│ │ │         ├──[-] items (28107:19)❌
│ │ │         ├──[M] type (28078:23)❌
│ │ │         ├──[-] minItems (28105:27)❌
│ │ │         └──[+] properties (28080:19)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (28246:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (27987:14)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (23329:20)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32986:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (28276:14)
│ ├─┬/repos/{owner}/{repo}/assignees
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18246:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (16596:20)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (20806:14)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (20837:14)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬output
│ │           └─┬annotations
│ │             └──[M] description (20912:36)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (16563:20)
│ ├─┬/enterprises/{enterprise}/code_security_and_analysis
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (5013:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (5043:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28321:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (28374:14)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27743:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (27791:14)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (21101:14)
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (12407:14)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33035:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (33075:14)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (38810:14)
│ ├─┬/repos/{owner}/{repo}/check-runs
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (20506:14)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬output
│ │           └─┬annotations
│ │             └──[M] description (20588:36)
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (27477:14)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (21402:14)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (21342:14)
│ ├─┬/repos/{owner}/{repo}/deployments
│ │ └─┬POST
│ │   └──[M] description (24344:20)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (8443:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27880:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (27928:14)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (26959:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (27055:14)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (29444:14)
│ ├─┬/enterprises/{enterprise}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (4584:20)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (21310:14)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28846:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28940:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (28880:14)
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│   └─┬POST
│     └──[M] description (30970:20)
├──check-run-rerequested
└──ping

Date: 07/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 104           | 24
❌ 24 Breaking changes out of 104

ERROR: breaking changes discovered