[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 098981175e8fbf0284572b5c5b4e6659) from 1.1.4 (hash: 80d27e9cd0e44460c206fbaa98f901e0) Detected Schema changes:
└─┬Components
  ├──[-] schemas (63852:7)❌
  └─┬code-scanning-alert-state
    └──[+] enum (63856:9)

Date: 06/24/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 1
❌ 1 Breaking changes out of 2

ERROR: breaking changes discovered