[GitHubEnterprise-3.9] Update to 1.1.4 (hash: b2a6a34dedaa0d9914e4baad000d7aa6) from 1.1.4 (hash: ef6250d64a7b98f4c7b1fca31893f33f) Detected Schema changes:
├─┬Paths
│ ├──[+] path (8237:3)
│ ├──[+] path (16532:3)
│ ├──[+] path (8104:3)
│ ├──[+] path (8329:3)
│ ├──[+] path (16486:3)
│ ├──[+] path (7984:3)
│ ├──[+] path (17834:3)
│ ├─┬/gitignore/templates
│ │ └──GET
│ ├─┬/users/{username}/docker/conflicts
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/authorizations/clients/{client_id}
│ │ └──PUT
│ ├─┬/repositories
│ │ └──GET
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions
│ │ └──GET
│ ├─┬/orgs/{org}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/repos
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├──GET
│ │ ├──PUT
│ │ ├──POST
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/pulls
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/users/{username}/hovercard
│ │ └──GET
│ ├─┬/licenses/{license}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/gists/starred
│ │ └──GET
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/keys
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/languages
│ │ └──GET
│ ├─┬/gists
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/dispatches
│ │ └──POST
│ ├─┬/user/packages/{package_type}/{package_name}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/docker/conflicts
│ │ └──GET
│ ├─┬/gists/{gist_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[+] additionalProperties (5636:37)
│ │         ├──[-] anyOf (5647:17)❌
│ │         ├──[-] anyOf (5645:17)❌
│ │         └─┬files
│ │           └──[M] additionalProperties (5620:21)
│ ├─┬/app-manifests/{code}/conversions
│ │ └──POST
│ ├─┬/app/installations
│ │ └──GET
│ ├─┬/orgs/{org}/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └──GET
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/app
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └──POST
│ ├─┬/projects/{project_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/transfer
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/vulnerability-alerts
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/issues
│ │ └──GET
│ ├─┬/zen
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/tags
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/topics
│ │ ├──GET
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├──GET
│ │ └──POST
│ ├─┬/search/commits
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/deployments
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/enterprises/{enterprise}/code-scanning/alerts
│ │ └──GET
│ ├─┬/markdown/raw
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └──GET
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/user/packages
│ │ └──GET
│ ├─┬/users/{username}/orgs
│ │ └──GET
│ ├─┬/app/installation-requests
│ │ └──GET
│ ├─┬/authorizations
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/emojis
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/merges
│ │ └──POST
│ ├─┬/orgs/{org}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/user/packages/{package_type}/{package_name}/versions
│ │ └──GET
│ ├─┬/orgs/{org}/audit-log
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head
│ │ └──GET
│ ├─┬/user
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/authorizations/clients/{client_id}/{fingerprint}
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └──GET
│ ├─┬/users/{username}/packages
│ │ └──GET
│ ├─┬/user/projects
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └──GET
│ ├─┬/teams/{team_id}/teams
│ │ └──GET
│ ├─┬/orgs/{org}/installation
│ │ └──GET
│ ├─┬/users/{username}/gists
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/projects
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/installation
│ │ └──GET
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └──POST
│ ├─┬/users/{username}/projects
│ │ └──GET
│ ├─┬/codes_of_conduct/{key}
│ │ └──GET
│ ├─┬/teams/{team_id}/repos
│ │ └──GET
│ ├─┬/app/installations/{installation_id}/suspended
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/users/{username}
│ │ └──GET
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/restore
│ │ └──POST
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/license
│ │ └──GET
│ ├─┬/organizations
│ │ └──GET
│ ├─┬/markdown
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/merge-upstream
│ │ └──POST
│ ├─┬/gists/{gist_id}/star
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├──GET
│ │ └──POST
│ ├─┬/applications/grants/{grant_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/teams/{team_slug}/teams
│ │ └──GET
│ ├─┬/search/labels
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/collaborators
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └──GET
│ ├─┬/rate_limit
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/orgs/{org}/teams
│ │ ├──GET
│ │ └──POST
│ ├─┬/authorizations/{authorization_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/gists/public
│ │ └──GET
│ ├─┬/gists/{gist_id}/commits
│ │ └──GET
│ ├─┬/user/teams
│ │ └──GET
│ ├─┬/user/repos
│ │ ├──GET
│ │ └──POST
│ ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pages/deployment
│ │ └──POST
│ ├─┬/octocat
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits
│ │ └──GET
│ ├─┬/applications/grants
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/repos
│ │ └──GET
│ ├─┬/teams/{team_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/update-branch
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/branches
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/keys/{key_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/
│ │ └──GET
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/user/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/gists/{gist_id}/{sha}
│ │ └──GET
│ ├─┬/gists/{gist_id}/forks
│ │ ├──GET
│ │ └──POST
│ ├─┬/app/installations/{installation_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └──POST
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └──GET
│ ├─┬/search/code
│ │ └──GET
│ ├─┬/gitignore/templates/{name}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/search/repositories
│ │ └──GET
│ ├─┬/apps/{app_slug}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/licenses
│ │ └──GET
│ ├─┬/user/orgs
│ │ └──GET
│ ├─┬/users/{username}/packages/{package_type}/{package_name}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/user/docker/conflicts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/codeowners/errors
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds/latest
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/replicas/caches
│ │ └──GET
│ ├─┬/codes_of_conduct
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/orgs/{org}/packages
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/restore
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └──GET
│ ├─┬/search/issues
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/users
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/contributors
│ │ └──GET
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/installation
│ │ └──GET
│ ├─┬/orgs/{org}/settings/billing/advanced-security
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/branches/{branch}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions
│ │ └──GET
│ ├─┬/teams/{team_id}/projects
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └──GET
│ ├─┬/user/packages/{package_type}/{package_name}/restore
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/meta
│ │ └──GET
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/search/users
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/merge
│ │ ├──GET
│ │ └──PUT
│ ├─┬/orgs/{org}/installations
│ │ └──GET
│ ├─┬/search/topics
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/deployments/{deployment_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/repos
│ │ ├──GET
│ │ └──POST
│ └─┬/repos/{owner}/{repo}/branches/{branch}/rename
│   └──POST
└─┬Components
  ├──[+] parameters (220432:7)
  ├──[+] parameters (220218:7)
  ├──[+] examples (204356:7)
  ├──[+] examples (204275:7)
  ├──[+] examples (201594:7)
  ├──[+] examples (201439:7)
  ├──[+] schemas (69892:7)
  └──[+] schemas (67379:7)

Date: 06/28/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 8             | 0
paths            | 11            | 2
❌ 2 Breaking changes out of 19

ERROR: breaking changes discovered