[GitHubEnterprise-3.7] Update to 1.1.4-99f7c55def8cb42085ac682fc71ab2d7 from 1.1.4-0a1e9a6e4e13b9cba9c50a64c18a4686 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (215991:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (57708:14)❌
│ │         └─┬default
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           └──[-] value (199877:9)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215991:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬GET
│ │   └──[M] description (26162:20)
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[M] value (1974:19)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (57708:14)❌
│ │         └─┬default
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[M] value (211066:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           └──[-] value (199877:9)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (215991:20)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (57708:14)❌
│ │         └─┬default
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[M] value (199869:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           ├──[-] value (199877:9)
│ │           └──[-] value (199877:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (13230:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (215991:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (215991:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (215991:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   ├─┬GET
│   │ └─┬Parameters
│   │   └──[M] description (215991:20)
│   └─┬POST
│     └─┬Parameters
│       └──[M] description (215991:20)
└─┬Components
  ├──[+] examples (211065:7)
  ├──[+] examples (199868:7)
  └─┬app-permissions
    └──[-] properties (56784:9)❌

Date: 11/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 289           | 3
components       | 3             | 1

❌  4 Breaking changes out of 292
INFO: Modifications: 269
INFO: Removals: 21
INFO: Additions: 2
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 3

ERROR: breaking changes discovered