[GitHubEnterprise-3.10] Update to 1.1.4-b2ef466c8136c419369cf159fdbf575b from 1.1.4-cc87d1aff5f6416c393a1e3366f8f3ec Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ ├─┬GET
│ │ │ └──[M] description (23606:20)
│ │ └─┬PATCH
│ │   └──[M] description (23642:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └──[M] description (23194:20)
│ │ └─┬PATCH
│ │   └──[M] description (23234:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (23420:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (23339:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (23295:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (23820:20)
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └─┬GET
│ │   └──[M] description (10161:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts
│   └─┬GET
│     └──[M] description (23116:20)
├──secret-scanning-alert-location-created
└─┬Components
  └─┬code-scanning-default-setup-update
    ├──[-] additionalProperties (74651:29)❌
    └─┬state
      └──[M] description (74638:24)

Date: 11/11/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 10            | 0
components       | 2             | 1

❌  1 Breaking changes out of 12
INFO: Modifications: 11
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered