[GitHubEnterprise-3.14] Update to 1.1.4-104eead85eed7e03a026852edc095233 from 1.1.4-d38aae92477e79392ec7b388fbc01e51 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/properties/schema
│ │ └─┬PATCH
│ │   └──[🔀] description (15128:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[➖] parameters (32131:15)❌
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (32279:17)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (32895:17)❌
│ └─┬/orgs/{org}/issues
│   └─┬GET
│     └──[➖] parameters (12715:15)❌
└─┬Components
  ├──[➖] schemas (71090:7)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_issue
  │     └──[➖] properties (127058:17)❌
  ├─┬webhook-issues-labeled
  │ └─┬issue
  │   └──[➖] properties (120781:13)❌
  ├─┬app-permissions
  │ └─┬dependabot_secrets
  │   └──[🔀] description (66877:24)
  ├─┬custom-property-set-payload
  │ └──[➖] properties (75800:9)❌
  ├─┬webhook-issues-locked
  │ └─┬issue
  │   └──[➖] properties (121774:13)❌
  ├─┬webhook-issues-closed
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (116759:15)❌
  ├─┬issue-search-result-item
  │ └──[➖] properties (89414:9)❌
  ├─┬webhook-issue-comment-deleted
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (114294:15)❌
  ├─┬webhook-issues-demilestoned
  │ └─┬issue
  │   └──[➖] properties (118848:13)❌
  ├─┬webhook-issues-deleted
  │ └─┬issue
  │   └──[➖] properties (117863:13)❌
  ├─┬webhooks_issue_2
  │ └──[➖] properties (95671:9)❌
  ├─┬webhook-issues-unlocked
  │ └─┬issue
  │   └──[➖] properties (128588:13)❌
  ├─┬webhook-issues-reopened
  │ └─┬issue
  │   └──[➖] properties (126198:13)❌
  ├─┬webhook-issue-comment-created
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (113081:15)❌
  ├─┬webhook-issues-opened
  │ └─┬issue
  │   └──[➖] properties (125105:13)❌
  ├─┬webhook-issues-edited
  │ └─┬issue
  │   └──[➖] properties (119812:13)❌
  ├─┬issue
  │ └──[➖] properties (71390:9)❌
  ├─┬webhooks_issue
  │ └──[➖] properties (94589:9)❌
  ├─┬webhook-issue-comment-edited
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (115514:15)❌
  └─┬webhook-issues-milestoned
    └─┬issue
      └──[➖] properties (122739:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 21            | 24               |

Date: 03/18/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _28_ out of _26_
- **Modifications**: _2_
- **Removals**: _24_
- **Breaking Removals**: _24_

ERROR: breaking changes discovered