[GitHubEnterprise-3.14] Update to 1.1.4-92f924d1a2fb4647ad6d28e98d13ef05 from 1.1.4-9e7e4db41342903bf3c77344139c3a4e Detected Schema changes:
```
└─┬Paths
  ├─┬/users/{username}
  │ └─┬GET
  │   └──[🔀] description (46710:20)
  ├─┬/orgs/{org}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (216785:20)
  │     └─┬Schema
  │       └──[➖] enum (216795:11)❌
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (216785:20)
  │     └─┬Schema
  │       └──[➖] enum (216795:11)❌
  ├─┬/repos/{owner}/{repo}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (216785:20)
  │     └─┬Schema
  │       └──[➖] enum (216795:11)❌
  └─┬/user/{account_id}
    └─┬GET
      └──[🔀] description (46627:20)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 3                |

Date: 01/16/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _8_
- **Modifications**: _5_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered