[GitHubEnterprise-3.8] Update to 1.1.4 (hash: a1ffd8a78284f3066064905b42991b32) from 1.1.4 (hash: 8ebcf2426510ae0cba956e33fdf5513b) Detected Schema changes:
├─┬Paths
│ ├──[+] path (8153:3)
│ ├──[+] path (7928:3)
│ ├──[+] path (7808:3)
│ ├──[+] path (8061:3)
│ ├──[+] path (15703:3)
│ ├──[+] path (15749:3)
│ ├──[+] path (16959:3)
│ ├─┬/repos/{owner}/{repo}/branches
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/tags
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/pulls
│ │ └──GET
│ ├─┬/app/installations/{installation_id}/suspended
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/collaborators
│ │ └──GET
│ ├─┬/orgs/{org}/installations
│ │ └──GET
│ ├─┬/meta
│ │ └──GET
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/gists/{gist_id}/{sha}
│ │ └──GET
│ ├─┬/orgs/{org}/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head
│ │ └──GET
│ ├─┬/search/issues
│ │ └──GET
│ ├─┬/codes_of_conduct/{key}
│ │ └──GET
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └──POST
│ ├─┬/markdown/raw
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/installation
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/keys/{key_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └──GET
│ ├─┬/orgs/{org}/repos
│ │ ├─┬GET
│ │ │ ├──[M] description (12501:20)
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └──application/json
│ │ └──POST
│ ├─┬/authorizations/clients/{client_id}/{fingerprint}
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/transfer
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/keys
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/orgs
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/user/issues
│ │ └──GET
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repositories
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/replicas/caches
│ │ └──GET
│ ├─┬/app
│ │ └──GET
│ ├─┬/orgs/{org}/migrations/{migration_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├──GET
│ │ ├──PUT
│ │ ├──POST
│ │ └──DELETE
│ ├─┬/orgs/{org}/teams/{team_slug}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/gists/{gist_id}/star
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/search/repositories
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/contributors
│ │ └──GET
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/app/installations
│ │ └──GET
│ ├─┬/orgs/{org}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/merge-upstream
│ │ └──POST
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └──GET
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/authorizations
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └──GET
│ ├─┬/markdown
│ │ └──POST
│ ├─┬/gitignore/templates
│ │ └──GET
│ ├─┬/zen
│ │ └──GET
│ ├─┬/orgs/{org}/installation
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └──GET
│ ├─┬/app/installations/{installation_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pages/deployment
│ │ └──POST
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/emojis
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/languages
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/topics
│ │ ├──GET
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └──GET
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └──GET
│ ├─┬/orgs/{org}/teams
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └──GET
│ ├─┬/orgs/{org}/audit-log
│ │ └──GET
│ ├─┬/
│ │ └──GET
│ ├─┬/teams/{team_id}/projects
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/merge
│ │ ├──GET
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/authorizations/{authorization_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/users/{username}/gists
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits
│ │ └──GET
│ ├─┬/projects/{project_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/search/code
│ │ └──GET
│ ├─┬/gists/{gist_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[+] additionalProperties (5615:37)
│ │         ├──[-] anyOf (5626:17)❌
│ │         ├──[-] anyOf (5624:17)❌
│ │         └─┬files
│ │           └──[M] additionalProperties (5599:21)
│ ├─┬/search/topics
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └──GET
│ ├─┬/user/repos
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/merges
│ │ └──POST
│ ├─┬/apps/{app_slug}
│ │ └──GET
│ ├─┬/gists
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/organizations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/installation
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/rename
│ │ └──POST
│ ├─┬/teams/{team_id}/teams
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/licenses
│ │ └──GET
│ ├─┬/octocat
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/branches/{branch}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/deployments
│ │ ├──GET
│ │ └──POST
│ ├─┬/enterprises/{enterprise}/code-scanning/alerts
│ │ └──GET
│ ├─┬/gists/starred
│ │ └──GET
│ ├─┬/user/subscriptions
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/orgs/{org}/teams/{team_slug}/projects
│ │ └──GET
│ ├─┬/search/labels
│ │ └──GET
│ ├─┬/users/{username}/hovercard
│ │ └──GET
│ ├─┬/applications/grants/{grant_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/user/orgs
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └──GET
│ ├─┬/app-manifests/{code}/conversions
│ │ └──POST
│ ├─┬/search/users
│ │ └──GET
│ ├─┬/user/migrations/{migration_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/search/commits
│ │ └──GET
│ ├─┬/teams/{team_id}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/applications/grants
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/deployments/{deployment_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/teams/{team_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/dispatches
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/gists/{gist_id}/commits
│ │ └──GET
│ ├─┬/licenses/{license}
│ │ └──GET
│ ├─┬/users
│ │ └──GET
│ ├─┬/app/installation-requests
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/codeowners/errors
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/codes_of_conduct
│ │ └──GET
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/gists/{gist_id}/forks
│ │ ├──GET
│ │ └──POST
│ ├─┬/authorizations/clients/{client_id}
│ │ └──PUT
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/user/teams
│ │ └──GET
│ ├─┬/user/projects
│ │ └──POST
│ ├─┬/rate_limit
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/gists/public
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/users/{username}/subscriptions
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ ├─┬/gitignore/templates/{name}
│ │ └──GET
│ ├─┬/users/{username}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/license
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/update-branch
│ │ └──PUT
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/user
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/orgs/{org}/settings/billing/advanced-security
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/pages/builds/latest
│ │ └──GET
│ ├─┬/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └──GET
│ └─┬/users/{username}/projects
│   └──GET
└─┬Components
  ├──[+] parameters (216250:7)
  ├──[+] parameters (216409:7)
  ├──[+] examples (198115:7)
  ├──[+] examples (200602:7)
  ├──[+] examples (197960:7)
  ├──[+] examples (200683:7)
  ├──[+] schemas (64732:7)
  ├──[+] schemas (67017:7)
  └─┬minimal-repository
    └──[+] properties (64181:9)

Date: 06/28/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 12            | 2
components       | 9             | 0
❌ 2 Breaking changes out of 21

ERROR: breaking changes discovered