[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 666ecf28261cc4d9a19b77a514f8de10) from 1.1.4 (hash: 4e3fa98a256d9145575f21bbaed82c9e) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (17358:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └──[M] description (35266:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/memberships/{username}
│ │ └─┬GET
│ │   └──[M] description (14493:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (18679:20)
│ │ └─┬POST
│ │   └──[M] description (18723:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (19065:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (8690:20)
│ │ └─┬DELETE
│ │   └──[M] description (8720:20)
│ ├─┬/user/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (39164:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (9305:20)
│ │ └─┬DELETE
│ │   └──[M] description (9337:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (18775:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (18847:20)
│ │ └─┬PATCH
│ │   └──[M] description (18805:20)
│ ├─┬/enterprises/{enterprise}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3854:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3883:14)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (219974:20)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}
│ │ └─┬GET
│ │   └──[M] description (16539:20)
│ ├─┬/orgs/{org}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (8974:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (26048:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (35312:20)
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (30814:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (30851:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (17402:20)
│ ├─┬/orgs/{org}/repository-fine-grained-permissions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (13153:14)
│ ├─┬/orgs/{org}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (9486:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (9577:20)
│ │ └─┬PATCH
│ │   └──[M] description (9516:20)
│ ├─┬/orgs/{org}/external-groups
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10779:14)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (8316:14)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (9696:20)
│ │ └─┬DELETE
│ │   └──[M] description (9729:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (26102:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (26134:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (26176:14)
│ ├─┬/user/ssh_signing_keys/{ssh_signing_key_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41666:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (41703:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (20601:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (35627:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (35699:20)
│ │ └─┬PATCH
│ │   └──[M] description (35657:20)
│ ├─┬/user/ssh_signing_keys
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41558:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (41602:14)
│ ├─┬/orgs/{org}/{security_product}/{enablement}
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (14997:14)
│ ├─┬/enterprises/{enterprise}/settings/billing/advanced-security
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5214:14)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (18379:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (17435:20)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (8744:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8818:20)
│ │ ├─┬POST
│ │ │ └──[M] description (8769:20)
│ │ └─┬DELETE
│ │   └──[M] description (8869:20)
│ ├─┬/orgs/{org}/external-group/{group_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10748:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (17468:20)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (30567:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (30682:14)
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (30599:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (30784:14)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   ├──[M] description (16834:20)
│ │   └─┬External Docs
│ │     └──[M] url (16842:14)
│ ├─┬/repos/{owner}/{repo}/tags/protection/{tag_protection_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (34756:14)
│ ├─┬/enterprise/stats/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3356:14)
│ ├─┬/user/packages
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (40571:14)
│ ├─┬/enterprise/stats/pulls
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3467:14)
│ ├─┬/user/social_accounts
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (41432:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (41498:14)
│ ├─┬/repos/{owner}/{repo}/tarball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (34785:14)
│ ├─┬/
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (128:14)
│ ├─┬/orgs/{org}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (8929:20)
│ ├─┬/orgs/{org}/announcement
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9772:14)
│ ├─┬/manage/v1/replication/status
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6554:14)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (26654:14)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (8619:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (42779:14)
│ ├─┬/user/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (40725:14)
│ ├─┬/repos/{owner}/{repo}/zipball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (35086:14)
│ ├─┬/projects/columns/{column_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (15302:14)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (12431:14)
│ ├─┬/orgs/{org}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (8587:20)
│ ├─┬/enterprise/stats/all
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3247:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/access
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (17161:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (17196:14)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (12469:14)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (15884:14)
│ ├─┬/orgs/{org}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7876:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7909:14)
│ ├─┬/projects/columns/cards/{card_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (15057:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (8896:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42667:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (30913:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (17559:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (17637:20)
│ │ ├─┬POST
│ │ │ └──[M] description (17586:20)
│ │ └─┬DELETE
│ │   └──[M] description (17690:20)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (8651:20)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (8362:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (18464:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (42741:14)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (12345:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (4022:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (18496:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (18527:20)
│ │ └─┬DELETE
│ │   └──[M] description (18655:20)
│ ├─┬/users/{username}/packages
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42502:14)
│ ├─┬/orgs/{org}/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10681:14)
│ ├─┬/manage/v1/config/nodes
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6513:14)
│ ├─┬/repos/{owner}/{repo}/actions/organization-variables
│ │ └─┬GET
│ │   └──[M] description (17028:20)
│ ├─┬/orgs/{org}/actions/permissions/workflow
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7943:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7974:14)
│ ├─┬/enterprises/{enterprise}/code_security_and_analysis
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5013:14)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6758:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (35531:20)
│ │ └─┬POST
│ │   └──[M] description (35575:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (21055:14)
│ ├─┬/users/{username}/docker/conflicts
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (42042:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (4242:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (4284:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (18418:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (17719:20)
│ ├─┬/organizations/{organization_id}/custom_roles
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (7198:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (9212:20)
│ │ └─┬PUT
│ │   └──[M] description (9254:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (18064:20)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (17230:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (17264:14)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (9601:20)
│ │ └─┬PUT
│ │   └──[M] description (9647:20)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (33368:14)
│ ├─┬/orgs/{org}/audit-log
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9860:14)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (8542:20)
│ ├─┬/setup/api/start
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (37425:14)
│ ├─┬/orgs/{org}/teams/{team_slug}/external-groups
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (14351:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (14429:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (14381:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (17501:20)
│ │ └─┬DELETE
│ │   └──[M] description (17533:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (9004:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (9034:20)
│ │ └─┬DELETE
│ │   └──[M] description (9188:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (20828:14)
│ ├─┬/orgs/{org}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (9370:20)
│ │ └─┬POST
│ │   └──[M] description (9414:20)
│ ├─┬/repos/{owner}/{repo}/tags/protection
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (34670:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (34705:14)
│ ├─┬/manage/v1/version
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6595:14)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (4700:14)
│ ├─┬/repos/{owner}/{repo}/actions/organization-secrets
│ │ └─┬GET
│ │   └──[M] description (16982:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (33068:14)
│ └─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│   ├─┬GET
│   │ └──[M] description (35345:20)
│   ├─┬PUT
│   │ └──[M] description (35376:20)
│   └─┬DELETE
│     └──[M] description (35507:20)
├─┬ping
│ └──POST
└─┬Components
  └──[-] responses (220303:7)❌

Date: 07/27/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 150           | 0
components       | 1             | 1
❌  1 Breaking changes out of 151
INFO: Modifications: 150
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered