[GitHubEnterprise-3.6] Update to 1.1.4 (hash: ff720eb2691cb25df16f1fb0074d307acurrent=2fedf890c75a0e319bf9af556ba723cc) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └─┬GET
│ │   ├──[-] description (31921:20)
│ │   └─┬Responses
│ │     └──[-] codes (81269:7)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (26247:20)
│ │ ├─┬POST
│ │ │ └──[-] description (26288:20)
│ │ └─┬DELETE
│ │   └──[-] description (26468:20)
│ ├─┬/repos/{owner}/{repo}/milestones
│ │ ├─┬GET
│ │ │ └──[-] description (27408:20)
│ │ └─┬POST
│ │   └──[-] description (27475:20)
│ ├─┬/user/memberships/orgs
│ │ └─┬GET
│ │   └──[-] description (36930:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ ├─┬GET
│ │ │ └──[-] description (11130:20)
│ │ └─┬DELETE
│ │   └──[-] description (11177:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └──[-] description (27660:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └──[-] description (26209:20)
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ └──[-] description (13449:20)
│ │ └─┬DELETE
│ │   └──[-] description (13534:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (32395:20)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └──[-] description (27064:20)
│ │ ├─┬DELETE
│ │ │ └──[-] description (27158:20)
│ │ └─┬PATCH
│ │   └──[-] description (27098:20)
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (26959:20)
│ │ └─┬POST
│ │   └──[-] description (26995:20)
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   └──[-] description (38604:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └──[-] description (26771:20)
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └──[-] description (25699:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └──[-] description (27546:20)
│ │ └─┬DELETE
│ │   └──[-] description (27636:20)
│ ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (22303:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ └──[-] description (13204:20)
│ │ └─┬DELETE
│ │   └──[-] description (13298:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (16410:20)
│ ├─┬/projects/{project_id}/columns
│ │ ├─┬GET
│ │ │ └──[-] description (14137:20)
│ │ └─┬POST
│ │   └──[-] description (14176:20)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └──[-] description (25736:20)
│ ├─┬/orgs/{org}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (9049:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (8499:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[-] codes (81281:7)❌
│ ├─┬/projects/columns/{column_id}/cards
│ │ └─┬GET
│ │   └──[-] description (13560:20)
│ └─┬/user/memberships/orgs/{org}
│   ├─┬GET
│   │ └──[-] description (36981:20)
│   └─┬PATCH
│     └──[-] description (37015:20)
└─┬Components
  └─┬api-overview
    └──[-] properties (44350:9)❌

Date: 06/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 38            | 2
components       | 1             | 1
❌ 3 Breaking changes out of 39

ERROR: breaking changes discovered