[GitHubEnterprise-3.14] Update to 1.1.4-4b8ff7792783a0592e25008fb6c20f98 from 1.1.4-f5ae341048327f8fa2b6a1ba017066cc Detected Schema changes:
```
├─┬Paths
│ ├─┬/scim/v2/enterprises/{enterprise}/Groups
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (40267:22)
│ └─┬/scim/v2/enterprises/{enterprise}/Users
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (40619:22)
└─┬Components
  ├─┬code-scanning-alert-items
  │ └──[➖] properties (81499:9)❌
  ├─┬code-scanning-organization-alert-items
  │ └──[➖] properties (70362:9)❌
  ├─┬webhook-code-scanning-alert-created
  │ └─┬alert
  │   └──[➖] properties (103928:13)❌
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └──[➖] properties (103632:13)❌
  └─┬code-scanning-alert
    └──[➖] properties (81608:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 0                |
| components       | 5             | 5                |

Date: 02/13/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _5_ out of _7_
- **Modifications**: _2_
- **Removals**: _5_
- **Breaking Removals**: _5_

ERROR: breaking changes discovered