[GitHubEnterprise-3.7] Update to 1.1.4-4e2a153d0943ec4d0ecafde3422b4940 from 1.1.4-459c78815195214803a3332657b9add6 Detected Schema changes:
├─┬Paths
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (69829:14)❌
├─┬user-created
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (55122:9)
├─┬user-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (55192:9)
└─┬Components
  └──[-] schemas (69829:7)❌

Date: 09/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
webhooks         | 2             | 0
components       | 1             | 1
❌  2 Breaking changes out of 4
INFO: Modifications: 3
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered