[GitHubEnterprise-3.15] Update to 1.1.4-65326b80112b8870ab78f284d1043862 from 1.1.4-2a1d0ccfe930b8ed692c2e9d0749415f Detected Schema changes:
```
└─┬Paths
  ├─┬/orgs/{org}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (217253:20)
  │     └─┬Schema
  │       └──[➖] enum (217263:11)❌
  ├─┬/users/{username}
  │ └─┬GET
  │   └──[🔀] description (47108:20)
  ├─┬/user/{account_id}
  │ └─┬GET
  │   └──[🔀] description (47025:20)
  ├─┬/repos/{owner}/{repo}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (217253:20)
  │     └─┬Schema
  │       └──[➖] enum (217263:11)❌
  └─┬/enterprises/{enterprise}/dependabot/alerts
    └─┬GET
      └─┬Parameters
        ├──[🔀] description (217253:20)
        └─┬Schema
          └──[➖] enum (217263:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 3                |

Date: 01/16/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _8_
- **Modifications**: _5_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered