[GitHubEnterprise-3.15] Update to 1.1.4-64f3614e3a2420f2e1d792c6db1487f6 from 1.1.4-304084ef72c17bb8078ef873b8a1f8e0 Detected Schema changes:
```
└─┬Paths
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (217252:20)
  │     └─┬Schema
  │       └──[➕] enum (217262:11)
  ├─┬/repos/{owner}/{repo}/dependabot/alerts
  │ └─┬GET
  │   ├──[➕] parameters (29084:15)❌
  │   ├──[➕] parameters (216989:13)❌
  │   ├──[➕] parameters (217278:13)❌
  │   ├──[➕] parameters (29092:15)❌
  │   ├──[➕] parameters (216998:13)❌
  │   ├──[➕] parameters (217265:13)❌
  │   └─┬Parameters
  │     ├──[🔀] description (217252:20)
  │     └─┬Schema
  │       └──[➕] enum (217262:11)
  └─┬/orgs/{org}/dependabot/alerts
    └─┬GET
      └─┬Parameters
        ├──[🔀] description (217252:20)
        └─┬Schema
          └──[➕] enum (217262:11)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 6                |

Date: 01/21/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _12_
- **Modifications**: _3_
- **Additions**: _9_
- **Breaking Additions**: _6_

ERROR: breaking changes discovered