[GitHubEnterprise-3.6] Update to 1.1.4 (hash: 12ea0f10e355760649fd4e1fab456ffa) from 1.1.4 (hash: ed4f169289a64f779c83855c01ccdfe1) Detected Schema changes:
└─┬Paths
  ├─┬/admin/ldap/teams/{team_id}/mapping
  │ └─┬PATCH
  │   └──[M] description (467:20)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
  │ └─┬POST
  │   ├──[M] description (29842:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬event
  │           └──[M] description (29880:32)
  ├─┬/repos/{owner}/{repo}/comments
  │ └─┬GET
  │   └──[M] description (21009:20)
  ├─┬/rate_limit
  │ └─┬GET
  │   ├──[M] description (14297:20)
  │   └─┬Responses
  │     └─┬200
  │       └─┬application/json
  │         └─┬default
  │           ├──[M] value (67450:9)
  │           └──[M] value (67450:9)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (25683:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (25695:22)
  │ └─┬POST
  │   ├──[M] description (25736:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (25758:32)
  ├─┬/repos/{owner}/{repo}/contents/{path}
  │ └─┬GET
  │   └──[M] description (21949:20)
  ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (12325:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (12341:22)
  │ └─┬POST
  │   ├──[M] description (12380:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (12404:32)
  ├─┬/repos/{owner}/{repo}/readme
  │ └─┬GET
  │   └──[M] description (30304:20)
  ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
  │ └─┬PUT
  │   └──[M] description (16523:20)
  ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
  │ └─┬PUT
  │   └──[M] description (22444:20)
  ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (29050:20)
  ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (12597:20)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
  │ └─┬POST
  │   └──[M] description (30174:20)
  ├─┬/repos/{owner}/{repo}/collaborators/{username}
  │ └─┬PUT
  │   └──[M] description (20847:20)
  ├─┬/orgs/{org}/actions/secrets/{secret_name}
  │ └─┬PUT
  │   └──[M] description (8543:20)
  ├─┬/zen
  │ └─┬GET
  │   └─┬Responses
  │     └─┬200
  │       ├──[+] content (39181:15)
  │       └──[-] content (38837:15)❌
  ├─┬/repos/{owner}/{repo}/releases/generate-notes
  │ └─┬POST
  │   └──[M] description (30633:20)
  ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (12449:20)
  ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (12476:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (12491:22)
  │ └─┬POST
  │   ├──[M] description (12530:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (12553:32)
  ├─┬/repos/{owner}/{repo}/readme/{dir}
  │ └─┬GET
  │   └──[M] description (30346:20)
  ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (28929:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (28941:22)
  │ └─┬POST
  │   ├──[M] description (28982:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (29004:32)
  ├─┬/teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (35104:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (35119:22)
  │ └─┬POST
  │   ├──[M] description (35161:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (35184:32)
  ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (31127:20)
  ├─┬/repos/{owner}/{repo}/git/trees/{tree_sha}
  │ └─┬GET
  │   ├──[M] description (24576:20)
  │   └─┬Parameters
  │     └──[-] description (24320:22)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
  │ └─┬PUT
  │   └──[M] description (30115:20)
  ├─┬/teams/{team_id}/discussions/{discussion_number}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (35222:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (35236:22)
  │ └─┬POST
  │   ├──[M] description (35278:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (35300:32)
  ├─┬/repos/{owner}/{repo}/releases/{release_id}/assets
  │ └─┬POST
  │   └──[M] description (30929:20)
  ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (31010:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (31022:22)
  │ └─┬POST
  │   ├──[M] description (31061:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (31083:32)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (26753:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (26765:22)
  │ └─┬POST
  │   ├──[M] description (26808:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (26830:32)
  ├─┬/orgs/{org}/dependabot/secrets/{secret_name}
  │ └─┬PUT
  │   └──[M] description (9112:20)
  ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ ├──[M] description (21147:20)
  │ │ └─┬Parameters
  │ │   └──[M] description (21159:22)
  │ └─┬POST
  │   ├──[M] description (21200:20)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬content
  │           └──[M] description (21222:32)
  ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
  │ └─┬PUT
  │   └──[M] description (32565:20)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
  │ └─┬GET
  │   └──[M] description (29076:20)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (25804:20)
  ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └──[M] description (21268:20)
  └─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
    └─┬DELETE
      └──[M] description (26876:20)

Date: 08/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 68            | 1
❌  1 Breaking changes out of 68
INFO: Modifications: 65
INFO: Removals: 2
INFO: Additions: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered