[GitHubEnterprise-3.6] Update to 1.1.4 (hash: 979c81d6eacf195adc4bf0c63782da12) from 1.1.4 (hash: cf1b70572b1ab7333e61ca043fe8d580) Detected Schema changes:
└─┬Components
  ├─┬organization-full
  │ └──[-] required (45189:9)❌
  └─┬team-organization
    └──[-] required (46528:9)❌

Date: 07/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌ 2 Breaking changes out of 2

ERROR: breaking changes discovered