[GitHubEnterprise-3.13] Update to 1.1.4-5d741a8b0df125cb7b16317ae5a0ff16 from 1.1.4-ffac604ed0c1f24261dd953b32c2fba3 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│ │ └─┬POST
│ │   └──[🔀] description (29122:20)
│ ├─┬/orgs/{org}/personal-access-token-requests
│ │ └─┬GET
│ │   └──[➖] parameters (215406:13)❌
│ └─┬/orgs/{org}/personal-access-tokens
│   └─┬GET
│     └──[➖] parameters (215406:13)❌
└─┬Components
  ├──[➖] parameters (215406:7)❌
  └─┬hook-delivery-item
    ├─┬repository_id
    │ └──[➖] format (67033:19)❌
    ├─┬id
    │ └──[➖] format (66972:19)❌
    └─┬installation_id
      └──[➖] format (67025:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 2                |
| components       | 4             | 4                |

Date: 03/12/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered