[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 080db22c18272a6bbe72c4096b08470d) from 1.1.4 (hash: 25ea147294926d95332642540f36b6e9) Detected Schema changes:
└─┬Paths
  ├─┬/user/docker/conflicts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (39169:14)
  ├─┬/orgs/{org}/packages/{package_type}/{package_name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (12244:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (12277:14)
  ├─┬/users/{username}/packages/{package_type}/{package_name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (42565:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (42598:14)
  ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (42784:14)
  ├─┬/enterprises/{enterprise}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (4584:20)
  ├─┬/orgs/{org}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (8657:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (28551:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (28587:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28974:14)
  ├─┬/user/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (39902:14)
  ├─┬/orgs/{org}/packages
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (12176:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (29536:14)
  ├─┬/users/{username}/packages
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (42507:14)
  ├─┬/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (6336:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (34132:14)
  ├─┬/repos/{owner}/{repo}/labels/{name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (29833:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (29927:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (29867:14)
  ├─┬/orgs/{org}/packages/{package_type}/{package_name}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (12314:14)
  ├─┬/repos/{owner}/{repo}/deployments
  │ └─┬POST
  │   └──[M] description (25331:20)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (30317:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (30407:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (30347:14)
  ├─┬/repos/{owner}/{repo}/issues/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28464:14)
  ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (12351:14)
  ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28501:14)
  ├─┬/enterprises/{enterprise}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (4622:20)
  ├─┬/users/{username}/docker/conflicts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (42047:14)
  ├─┬/user/packages/{package_type}/{package_name}/versions
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (40730:14)
  ├─┬/users/{username}/packages/{package_type}/{package_name}/versions
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (42672:14)
  ├─┬/user/packages
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (40576:14)
  ├─┬/repos/{owner}/{repo}/assignees
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19124:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22201:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (23997:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28831:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (28867:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (28915:14)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   ├─┬External Docs
  │   │ └──[M] url (21365:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (21447:36)
  ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (12403:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (12437:14)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
  │ └─┬POST
  │   └──[M] description (31957:20)
  ├─┬/enterprises/{enterprise}/{security_product}/{enablement}
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (5248:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (33979:14)
  ├─┬/repos/{owner}/{repo}/milestones
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (30179:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (30246:14)
  ├─┬/orgs/{org}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (13193:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (29012:14)
  │ ├─┬PUT
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (29143:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       └─┬ONEOF
  │ │         └─┬labels
  │ │           └──[M] description (29159:34)
  │ ├─┬POST
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (29054:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ ├──[+] items (29081:19)❌
  │ │       │ ├──[M] type (29078:23)❌
  │ │       │ ├──[+] minItems (29079:27)❌
  │ │       │ └──[-] properties (29064:19)❌
  │ │       └─┬ONEOF
  │ │         ├──[-] items (29078:19)❌
  │ │         ├──[M] type (29065:23)❌
  │ │         ├──[-] minItems (29076:27)❌
  │ │         └──[+] properties (29067:19)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (29233:14)
  ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (40781:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (40813:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
  │ ├─┬PUT
  │ │ └─┬External Docs
  │ │   └──[M] url (29308:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (29361:14)
  ├─┬/user/packages/{package_type}/{package_name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (40629:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (40660:14)
  ├─┬/orgs/{org}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (8619:20)
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   ├──[M] description (22039:20)
  │   └─┬External Docs
  │     └──[M] url (22048:14)
  ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (12475:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (17441:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (21665:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (21696:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (21771:36)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   ├──[M] description (22095:20)
  │   └─┬External Docs
  │     └──[M] url (22106:14)
  ├─┬/repos/{owner}/{repo}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (29728:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (29766:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (29263:14)
  ├─┬/enterprises/{enterprise}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (5165:14)
  ├─┬/orgs/{org}/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (11384:14)
  ├─┬/search/code
  │ └─┬GET
  │   └──[M] description (36419:20)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (22261:14)
  ├─┬/repos/{owner}/{repo}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19166:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (30431:14)
  ├─┬/enterprises/{enterprise}/code_security_and_analysis
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (5013:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (5043:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (24062:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21960:14)
  ├─┬/repos/{owner}/{repo}/contents/{path}
  │ └─┬GET
  │   └──[M] description (24281:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
  │ ├─┬POST
  │ │ └─┬External Docs
  │ │   └──[M] url (28730:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (28778:14)
  ├─┬/users/{username}/packages/{package_type}/{package_name}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (42635:14)
  ├─┬/user/packages/{package_type}/{package_name}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (40694:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (17474:20)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (28217:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (28295:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (28248:14)
  ├─┬/repos/{owner}/{repo}/issues
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27946:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (28042:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (22001:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (34028:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (34068:14)
  ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (40848:14)
  ├─┬/repos/{owner}/{repo}/issues/comments
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28166:14)
  ├─┬/orgs/{org}/docker/conflicts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (10687:14)
  ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (42712:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (42746:14)
  └─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
    └─┬GET
      └─┬External Docs
        └──[M] url (22169:14)

Date: 07/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 111           | 7
❌ 7 Breaking changes out of 111

ERROR: breaking changes discovered