[GitHubEnterprise-3.13] Update to 1.1.4-50b5f868629d9d1260dbd8cc8a0f7a02 from 1.1.4-21328c477fcf59892ec22f32ff4cf8b7 Detected Schema changes:
```
├─┬Paths
│ ├─┬/scim/v2/enterprises/{enterprise}/Groups
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (39648:22)
│ └─┬/scim/v2/enterprises/{enterprise}/Users
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (40000:22)
└─┬Components
  ├─┬code-scanning-organization-alert-items
  │ └──[➖] properties (69402:9)❌
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └──[➖] properties (101849:13)❌
  ├─┬webhook-code-scanning-alert-created
  │ └─┬alert
  │   └──[➖] properties (102145:13)❌
  ├─┬code-scanning-alert
  │ └──[➖] properties (80243:9)❌
  └─┬code-scanning-alert-items
    └──[➖] properties (80134:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 0                |
| components       | 5             | 5                |

Date: 02/13/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _5_ out of _7_
- **Modifications**: _2_
- **Removals**: _5_
- **Breaking Removals**: _5_

ERROR: breaking changes discovered