[GitHubEnterprise-3.10] Update to 1.1.4-a72c72818770d1a41a217bc350cfb2ca from 1.1.4-b2ef466c8136c419369cf159fdbf575b Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (15516:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ └─┬/repos/{owner}/{repo}/code-scanning/sarifs
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[-] additionalProperties (23774:37)❌
│           └─┬ref
│             └──[M] $ref (65025:13)❌
└─┬Components
  ├──[-] schemas (74670:7)❌
  └─┬code-scanning-ref
    └──[M] description (65026:20)

Date: 11/16/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered