[GitHubEnterprise-3.5] Update to 1.1.4 (hash: a21d39699884865a10804a02a66c5b60) from 1.1.4 (hash: c63d5de05b0a9e0b9f4aabbabb220c53) Detected Schema changes:
└─┬Paths
  ├─┬/search/code
  │ └─┬GET
  │   └──[M] description (32190:20)
  ├─┬/orgs/{org}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (8007:20)
  ├─┬/repos/{owner}/{repo}/milestones
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27028:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (27095:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25861:14)
  │ ├─┬PUT
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (25992:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       └─┬ONEOF
  │ │         └─┬labels
  │ │           └──[M] description (26008:34)
  │ ├─┬POST
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (25903:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ ├──[+] items (25930:19)❌
  │ │       │ ├──[M] type (25927:23)❌
  │ │       │ ├──[+] minItems (25928:27)❌
  │ │       │ └──[-] properties (25913:19)❌
  │ │       └─┬ONEOF
  │ │         ├──[-] items (25927:19)❌
  │ │         ├──[M] type (25914:23)❌
  │ │         ├──[-] minItems (25925:27)❌
  │ │         └──[+] properties (25916:19)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26082:14)
  ├─┬/repos/{owner}/{repo}/issues/comments
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25015:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26112:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19498:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (30860:14)
  ├─┬/repos/{owner}/{repo}/deployments
  │ └─┬POST
  │   └──[M] description (22188:20)
  ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25350:14)
  ├─┬/repos/{owner}/{repo}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16503:14)
  ├─┬/repos/{owner}/{repo}/issues/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25313:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25716:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (25764:14)
  ├─┬/repos/{owner}/{repo}/issues
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (24795:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (24891:14)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25066:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (25144:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (25097:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21197:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
  │ ├─┬PUT
  │ │ └─┬External Docs
  │ │   └──[M] url (26157:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26210:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25400:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (25436:14)
  ├─┬/orgs/{org}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (8045:20)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19530:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26385:14)
  ├─┬/repos/{owner}/{repo}/assignees
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16461:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (15016:20)
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   ├──[M] description (19368:20)
  │   └─┬External Docs
  │     └──[M] url (19377:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
  │ ├─┬POST
  │ │ └─┬External Docs
  │ │   └──[M] url (25579:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (25627:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25823:14)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
  │ └─┬POST
  │   └──[M] description (28724:20)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (30761:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (30801:14)
  ├─┬/repos/{owner}/{repo}/contents/{path}
  │ └─┬GET
  │   └──[M] description (21481:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (25680:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (14983:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (19289:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (30716:14)
  ├─┬/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (6014:14)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   ├─┬External Docs
  │   │ └──[M] url (18694:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (18776:36)
  ├─┬/enterprises/{enterprise}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (4549:20)
  ├─┬/enterprises/{enterprise}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (4511:20)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   ├──[M] description (19424:20)
  │   └─┬External Docs
  │     └──[M] url (19435:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (27280:14)
  ├─┬/enterprises/{enterprise}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (4875:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (19330:14)
  ├─┬/orgs/{org}/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (9907:14)
  ├─┬/repos/{owner}/{repo}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26577:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (26615:14)
  ├─┬/repos/{owner}/{repo}/labels/{name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26682:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (26776:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (26716:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21262:14)
  ├─┬/user/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (35641:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27166:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (27256:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (27196:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (18994:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (19025:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (19100:36)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (19590:14)
  └─┬/orgs/{org}/secret-scanning/alerts
    └─┬GET
      └─┬External Docs
        └──[M] url (11348:14)

Date: 07/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.5/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.5/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 81            | 7
❌ 7 Breaking changes out of 81

ERROR: breaking changes discovered