[GitHubEnterprise-3.13] Update to 1.1.4-bb7bf23ece23a331cf9ec11f8b281329 from 1.1.4-8089ef8f95a445cc86353674bade2e6e Detected Schema changes:
```
└─┬Components
  ├─┬code-scanning-default-setup
  │ └─┬languages
  │   └─┬Schema
  │     └──[➖] enum (80374:15)❌
  └─┬code-scanning-default-setup-update
    └─┬languages
      └─┬Schema
        └──[➖] enum (80429:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |

Date: 12/20/24 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered