[GitHubEnterprise-3.14] Update to 1.1.4-bfa60ec3e74b1fce4fd15feaad5f7d6c from 1.1.4-c6bac21f127e4771c961c4af72e21fc4 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/personal-access-tokens
│ │ └─┬GET
│ │   └──[➖] parameters (217369:13)❌
│ ├─┬/orgs/{org}/personal-access-token-requests
│ │ └─┬GET
│ │   └──[➖] parameters (217369:13)❌
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│   └─┬POST
│     └──[🔀] description (29741:20)
└─┬Components
  ├──[➖] parameters (217369:7)❌
  └─┬hook-delivery-item
    ├─┬id
    │ └──[➖] format (67932:19)❌
    ├─┬installation_id
    │ └──[➖] format (67985:19)❌
    └─┬repository_id
      └──[➖] format (67993:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 2                |
| components       | 4             | 4                |

Date: 03/12/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered