[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 0048e453b0a490b3a38d05a669c7dac9) from 1.1.4 (hash: f514a0d8bdad4979912a5a964d52eb91) Detected Schema changes:
└─┬Components
  ├─┬webhook-check-suite-rerequested
  │ └──[+] properties (84790:9)
  ├─┬team-organization
  │ └──[-] required (68234:9)❌
  ├─┬organization-full
  │ └──[-] required (66823:9)❌
  ├─┬webhook-check-suite-completed
  │ └──[+] properties (83557:9)
  └─┬webhook-check-suite-requested
    └──[+] properties (84174:9)

Date: 07/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 5             | 2
❌ 2 Breaking changes out of 5

ERROR: breaking changes discovered