[GitHubEnterprise-3.15] Update to 1.1.4-3d1d0aa20a5ebee462aa16b1bf828099 from 1.1.4-13765a979ded08b549109e71b65bcfcf Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (205716:9)
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (11808:17)❌
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (11489:17)❌
│ └─┬/orgs/{org}
│   └─┬GET
│     └──[🔀] description (8461:20)
└─┬Components
  ├──[➖] schemas (77316:7)❌
  ├─┬code-security-configuration
  │ └──[➖] properties (74834:9)❌
  └─┬repository-rule-params-required-reviewer-configuration
    ├──[➕] required (77316:9)❌
    ├──[➕] properties (77310:9)
    └──[➖] properties (77349:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 2                |
| components       | 5             | 4                |

Date: 02/27/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _9_
- **Modifications**: _2_
- **Removals**: _5_
- **Additions**: _2_
- **Breaking Removals**: _5_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered