[GitHubEnterprise-3.9] Update to 1.1.4-e3ae2eae2c90874f12f8f08e4712f7e3 from 1.1.4-4ccf8822447f63e51189ec6bc939a5f5 Detected Schema changes:
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (111117:17)❌
        └──[-] properties (111389:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered