[GitHubEnterprise-3.15] Update to 1.1.4-6ea130cb5afd29dda26a543a1de89424 from 1.1.4-b323588c4cb3168432ec55824c9b764c Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│   └─┬POST
│     └─┬Extensions
│       └──[🔀] x-github (34555:9)
└─┬Components
  └─┬announcement
    └──[➖] properties (69559:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 1             | 1                |

Date: 02/12/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _2_
- **Modifications**: _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered