[GitHubEnterprise-3.10] Update to 1.1.4-cc87d1aff5f6416c393a1e3366f8f3ec from 1.1.4-063d863c411b077346786d787048d703 Detected Schema changes:
├─┬Paths
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-extra-repository-information
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           ├──[M] value (221149:9)
│ │           └──[+] value (221149:9)
│ ├─┬/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default-response
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           ├──[M] value (209413:9)
│ │           └──[+] value (209413:9)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28239:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (28263:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (28277:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28362:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (28653:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28674:9)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[M] value (219572:9)
│ │ │         ├──[M] value (219572:9)
│ │ │         ├──[M] value (219572:9)
│ │ │         ├──[M] value (219572:9)
│ │ │         ├──[M] value (219572:9)
│ │ │         ├──[+] value (219572:9)
│ │ │         ├──[+] value (219572:9)
│ │ │         ├──[+] value (219572:9)
│ │ │         ├──[+] value (219572:9)
│ │ │         ├──[+] value (219572:9)
│ │ │         └──[+] value (219572:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[M] value (219590:9)
│ │           ├──[+] value (219590:9)
│ │           └──[+] value (219590:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (28611:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28640:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28528:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (28544:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (28559:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28597:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (28715:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28726:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-repository-permissions
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           ├──[M] value (208950:9)
│ │           └──[+] value (208950:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28376:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (28394:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (28501:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (28512:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (28409:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28489:9)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (210593:9)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[-] codes (225764:7)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (28742:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (28753:9)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (210593:9)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│   └─┬POST
│     ├─┬External Docs
│     │ └──[M] url (28687:14)
│     └─┬Extensions
│       └──[M] x-github (28701:9)
├─┬pull-request-edited
│ └─┬POST
│   └──[M] description (55126:20)
└─┬Components
  ├─┬webhook-push
  │ └─┬repository
  │   └──[-] properties (184861:13)❌
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └──[-] properties (192983:13)❌
  ├─┬webhook-fork
  │ └─┬forkee
  │   └─┬ALLOF
  │     └──[-] properties (97839:15)❌
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └──[-] properties (113127:17)❌
  ├─┬repository-webhooks
  │ └──[-] properties (84592:9)❌
  ├─┬webhook-team-removed-from-repository
  │ └─┬repository
  │   └──[-] properties (195459:13)❌
  ├─┬job
  │ └─┬status
  │   └──[-] enum (71920:13)❌
  ├─┬team-repository
  │ └──[+] properties (70831:9)
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └──[-] properties (117471:17)❌
  ├─┬webhook-team-created
  │ └─┬repository
  │   └──[-] properties (193585:13)❌
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └──[-] properties (194188:13)❌
  └─┬webhook-team-edited
    └─┬repository
      └──[-] properties (194855:13)❌

Date: 11/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 12            | 12
paths            | 106           | 1
webhooks         | 1             | 0
❌  13 Breaking changes out of 119
INFO: Modifications: 95
INFO: Removals: 12
INFO: Additions: 12
INFO: Breaking Removals: 12

ERROR: breaking changes discovered