[GitHubEnterprise-3.14] Update to 1.1.4-560f263b37d18da211a6122a0343d80c from 1.1.4-401e653a83ab83c1b17a4df959fec270 Detected Schema changes:
```
└─┬Paths
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (216784:20)
  │     └─┬Schema
  │       └──[➕] enum (216794:11)
  ├─┬/orgs/{org}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (216784:20)
  │     └─┬Schema
  │       └──[➕] enum (216794:11)
  └─┬/repos/{owner}/{repo}/dependabot/alerts
    └─┬GET
      ├──[➕] parameters (216797:13)❌
      ├──[➕] parameters (216530:13)❌
      ├──[➕] parameters (28219:15)❌
      ├──[➕] parameters (28227:15)❌
      ├──[➕] parameters (216521:13)❌
      ├──[➕] parameters (216810:13)❌
      └─┬Parameters
        ├──[🔀] description (216784:20)
        └─┬Schema
          └──[➕] enum (216794:11)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 6                |

Date: 01/21/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _12_
- **Modifications**: _3_
- **Additions**: _9_
- **Breaking Additions**: _6_

ERROR: breaking changes discovered