[GitHubEnterprise-3.13] Update to 1.1.4-398d18348d48e9783363f49ed8fadd49 from 1.1.4-137676a6235fb7b69c005e84a24e1466 Detected Schema changes:
```
└─┬Paths
  ├─┬/users/{username}
  │ └─┬GET
  │   └──[🔀] description (46091:20)
  ├─┬/user/{account_id}
  │ └─┬GET
  │   └──[🔀] description (46008:20)
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (214873:20)
  │     └─┬Schema
  │       └──[➖] enum (214883:11)❌
  ├─┬/orgs/{org}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (214873:20)
  │     └─┬Schema
  │       └──[➖] enum (214883:11)❌
  └─┬/repos/{owner}/{repo}/dependabot/alerts
    └─┬GET
      └─┬Parameters
        ├──[🔀] description (214873:20)
        └─┬Schema
          └──[➖] enum (214883:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 3                |

Date: 01/16/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _8_
- **Modifications**: _5_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered