[GitHubEnterprise-3.9] Update to 1.1.4-7f570be2c0862d4a45b4a404eb9231e7 from 1.1.4-587bd15b6e95b6aed1db81f8bc886cf9 Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/migrations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬exclude
│ │           └──[M] description (11751:32)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         └──[M] value (212964:9)
│   └─┬PUT
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (212964:9)
└─┬Components
  ├─┬webhook-code-scanning-alert-appeared-in-branch
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (86678:28)
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (86359:28)
  ├─┬webhook-deployment-status-created
  │ └─┬check_run
  │   └─┬conclusion
  │     └──[M] description (92167:28)
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[+] properties (75071:17)
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (85752:28)
  ├─┬full-repository
  │ └──[+] required (69942:9)❌
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (87443:28)
  ├─┬code-scanning-default-setup
  │ └─┬languages
  │   └──[M] description (72796:24)
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (85138:28)
  └─┬webhook-code-scanning-alert-closed-by-user
    └─┬alert
      └─┬dismissed_reason
        └──[M] description (86936:28)

Date: 10/05/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 0
components       | 10            | 1
❌  1 Breaking changes out of 13
INFO: Modifications: 11
INFO: Additions: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered