[GitHubEnterprise-3.7] Update to 1.1.4 (hash: 2a371a4f6cd046023d123d932b8186eb) from 1.1.4 (hash: b721988e35edc0c3b4b62a736396981b) Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (8398:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8472:20)
│ │ ├─┬POST
│ │ │ └──[M] description (8423:20)
│ │ └─┬DELETE
│ │   └──[M] description (8523:20)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (24504:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (15893:20)
│ │ └─┬DELETE
│ │   └──[M] description (15925:20)
│ ├─┬/user/ssh_signing_keys/{ssh_signing_key_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (38714:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (38751:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (15951:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16029:20)
│ │ ├─┬POST
│ │ │ └──[M] description (15978:20)
│ │ └─┬DELETE
│ │   └──[M] description (16082:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (19248:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (28763:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/access
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (15554:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (15588:14)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (8273:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (19011:14)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (8016:14)
│ ├─┬/orgs/{org}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7530:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7563:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (4022:14)
│ ├─┬/repos/{owner}/{repo}/tags/protection
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (32477:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (32512:14)
│ ├─┬/enterprise/stats/all
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3247:14)
│ ├─┬/organizations/{organization_id}/custom_roles
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6891:14)
│ ├─┬/orgs/{org}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (8241:20)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7970:14)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (31192:14)
│ ├─┬/orgs/{org}/teams/{team_slug}/external-groups
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (12853:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (12931:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (12883:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28664:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (28701:14)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (14386:14)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (8305:20)
│ ├─┬/orgs/{org}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (8583:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (33082:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (33113:20)
│ │ └─┬DELETE
│ │   └──[M] description (33244:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (17264:14)
│ ├─┬/orgs/{org}/actions/permissions/workflow
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7597:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7628:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18784:14)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28417:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28532:14)
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28449:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (28634:14)
│ ├─┬/repos/{owner}/{repo}/zipball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32823:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (15827:20)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (4242:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (4284:14)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (16771:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (8658:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8688:20)
│ │ └─┬DELETE
│ │   └──[M] description (8842:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (15860:20)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6454:14)
│ ├─┬/setup/api/start
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (34969:14)
│ ├─┬/projects/columns/{column_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (13804:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (8550:20)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (213058:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (16810:20)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (15622:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (15656:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (8344:20)
│ │ └─┬DELETE
│ │   └──[M] description (8374:20)
│ ├─┬/repos/{owner}/{repo}/tags/protection/{tag_protection_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (32563:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (8866:20)
│ │ └─┬PUT
│ │   └──[M] description (8908:20)
│ ├─┬/orgs/{org}/audit-log
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9037:14)
│ ├─┬/orgs/{org}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (8628:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (13559:14)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (8196:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (23952:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (23984:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (24026:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (16856:20)
│ ├─┬/enterprises/{enterprise}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3854:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3883:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (15750:20)
│ ├─┬/enterprise/stats/pulls
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3467:14)
│ ├─┬/orgs/{org}/{security_product}/{enablement}
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (13499:14)
│ ├─┬/orgs/{org}/external-group/{group_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9617:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (8959:20)
│ │ └─┬DELETE
│ │   └──[M] description (8991:20)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (4700:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (33049:20)
│ ├─┬/user/ssh_signing_keys
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (38606:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (38650:14)
│ ├─┬/
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (128:14)
│ ├─┬/orgs/{org}/teams/{team_slug}/memberships/{username}
│ │ └─┬GET
│ │   └──[M] description (12995:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (16111:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (16456:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (15794:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (23898:14)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}
│ │ └─┬GET
│ │   └──[M] description (15035:20)
│ ├─┬/enterprise/stats/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3356:14)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   ├──[M] description (15330:20)
│ │   └─┬External Docs
│ │     └──[M] url (15338:14)
│ ├─┬/orgs/{org}/external-groups
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9648:14)
│ ├─┬/repos/{owner}/{repo}/tarball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32592:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (16888:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16919:20)
│ │ └─┬DELETE
│ │   └──[M] description (17047:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (30904:14)
│ ├─┬/enterprises/{enterprise}/settings/billing/advanced-security
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5062:14)
│ └─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│   └─┬GET
│     └──[M] description (33003:20)
└─┬Components
  └──[-] responses (213315:7)❌

Date: 07/27/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 109           | 0
components       | 1             | 1
❌  1 Breaking changes out of 110
INFO: Modifications: 109
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered