[GitHubEnterprise-3.14] Update to 1.1.4-f5ae341048327f8fa2b6a1ba017066cc from 1.1.4-dc977c8003154234e7a787ec7b8ad5db Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│   └─┬POST
│     └─┬Extensions
│       └──[🔀] x-github (33690:9)
└─┬Components
  └─┬announcement
    └──[➖] properties (69150:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 1             | 1                |

Date: 02/12/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _2_
- **Modifications**: _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered