[GitHubEnterprise-3.7] Update to 1.1.4 (hash: a92c593ffec4cc217b4373c471374c58) from 1.1.4 (hash: e95743a98b5ab7726b8448e47f7a0aa8) Detected Schema changes:
└─┬Components
  ├─┬webhook-check-suite-requested
  │ └──[+] properties (79109:9)
  ├─┬organization-full
  │ └──[-] required (62307:9)❌
  ├─┬webhook-check-suite-completed
  │ └──[+] properties (78492:9)
  ├─┬webhook-check-suite-rerequested
  │ └──[+] properties (79725:9)
  └─┬team-organization
    └──[-] required (63408:9)❌

Date: 07/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 5             | 2
❌ 2 Breaking changes out of 5

ERROR: breaking changes discovered