[GitHubEnterprise-3.8] Update to 1.1.4-bfe07fa9297679d9c211c13259099b65 from 1.1.4-adb21af56013cccf241f3c088108ef21 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (13969:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[-] additionalProperties (21903:37)❌
│ │         └─┬ref
│ │           └──[M] $ref (61021:13)❌
│ └─┬/repos/{owner}/{repo}/code-scanning/analyses
│   └─┬GET
│     └──Parameters
└─┬Components
  ├──[-] schemas (69868:7)❌
  └─┬code-scanning-ref
    └──[M] description (61022:20)

Date: 11/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered