[GitHubEnterprise-3.15] Update to 1.1.4-882141f1b59adcc27a5ddb1aac77be7c from 1.1.4-83e5b632882630eb5ec8d27318fd0346 Detected Schema changes:
```
├─┬Paths
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (196066:9)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (196066:9)
│ ├─┬/enterprises/{enterprise}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (218496:7)❌
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           └──[➖] value (196174:9)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           └──[➖] value (196174:9)
│ ├─┬/repos/{owner}/{repo}/pages/deployments
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[➕] value (36057:19)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (218496:7)❌
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (196066:9)
│ ├─┬/orgs/{org}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (218496:7)❌
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           ├──[🔀] value (196165:9)
│ │           └──[➖] value (196174:9)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (196066:9)
│ └─┬/enterprises/{enterprise}/actions/runners
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (196066:9)
└─┬Components
  └─┬runner
    └──[➖] properties (69994:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 27            | 3                |
| components       | 1             | 1                |

Date: 02/06/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _28_
- **Modifications**: _20_
- **Removals**: _7_
- **Additions**: _1_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered