[GitHubEnterprise-3.10] Update to 1.1.4-555826d732f1ad540de82cdc172b80ec from 1.1.4-4870bf04578a98f63b340584e8c69792 Detected Schema changes:
├──Paths
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (113179:17)❌
        └──[-] properties (113451:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 0             | 0
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered