[GitHubEnterprise-3.14] Update to 1.1.4-4d3a9ded7363917824fb2d5fa79ad2ce from 1.1.4-560f263b37d18da211a6122a0343d80c Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/dependabot/alerts/{alert_number}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[🔀] value (206759:9)
│             ├──[➕] value (206759:9)
│             ├──[➕] value (206759:9)
│             ├──[➕] value (206759:9)
│             ├──[➕] value (206759:9)
│             └──[➕] value (206759:9)
└─┬Components
  ├──[➖] schemas (67405:7)❌
  └─┬global-advisory
    └─┬epss
      └──[🔀] $ref (67594:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 0                |
| components       | 2             | 2                |

Date: 01/25/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _14_
- **Modifications**: _8_
- **Removals**: _1_
- **Additions**: _5_
- **Breaking Removals**: _1_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered