[GitHubEnterprise-3.11] Update to 1.1.4-c4df960383e22391af612472d81b5566 from 1.1.4-dff2b8597d2311abab3eaa64d211e5a3 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 5f3843
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           ├──[+] properties (28943:21)
│ │           └──[+] properties (28939:21)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             └──[M] $ref (29055:19)❌
└─┬Components
  └─┬hook
    └─┬config
      └──[M] $ref (79872:11)❌

Date: 01/13/24 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 1
components       | 1             | 1

❌  2 Breaking changes out of 4
INFO: Modifications: 2
INFO: Additions: 2
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered