[GitHubEnterprise-3.9] Update to 1.1.4-7a6078b4115cacf8a6a96b0c41f6a05f from 1.1.4-09701621217da81af78d6285dd561ac1 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit f52a0c
                                                                                SPEC: extracted 2 commits from history
                                                                                └─┬Paths
  └─┬/repos/{owner}/{repo}/autolinks
    └─┬GET
      ├──[+] parameters (222254:13)❌
      ├──[M] summary (19186:16)
      ├──[M] description (19187:20)
      └─┬External Docs
        └──[M] url (19196:14)

Date: 02/02/24 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1

❌  1 Breaking changes out of 4
INFO: Modifications: 3
INFO: Additions: 1
INFO: Breaking Additions: 1

DONE: completed

ERROR: breaking changes discovered